### ISSUE TITLE
mailproxy_release/main.go:112:35: invalid indirect of mailproxyDir (type string)

### ISSUE THREAD

**Issue by NullByteSuiteDevs** [katzenpost/mailproxy_release#3]
When attempting to build the mailproxy I get the following error:

`# github.com/katzenpost/mailproxy_release
bin/src/github.com/katzenpost/mailproxy_release/main.go:112:35: invalid indirect of mailproxyDir (type string)`

I'm trying to establish a client for a mixnet. Originally I tried the mailproxy repo, but found that it did not have any build instructions. While attempting to build the program I received the above error, I can provide more debugging information as needed.

**Comment by david415** [comment]
we use vendoring to perform our release builds and this process is documented. if you want us to give you free tech support then post to our mailing list or join our IRC channel. there is also a HACKING guide for new Katzenpost developers and it doesn't seem like you've review these documents which would be a polite thing to do before asking for help.
